version: '3.8'

services:
  # Servicio principal de Orbix AI
  orbix:
    build: .
    container_name: orbix-ai
    ports:
      - "80:8000"
    env_file:
      - .env
    restart: always
    volumes:
      - ./orbix_config.json:/app/orbix_config.json:ro
    depends_on:
      - postgres
    networks:
      - orbix-network

  # Base de datos PostgreSQL para Odoo
  postgres:
    image: postgres:13
    container_name: orbix-postgres
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo_password_2025
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql:ro
    ports:
      - "5432:5432"
    restart: always
    networks:
      - orbix-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d odoo"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Odoo para testing de validaciones de tarjetas (Babel)
  odoo:
    image: odoo:16.0
    container_name: orbix-odoo
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8070:8069"
    environment:
      - HOST=postgres
      - USER=odoo
      - PASSWORD=odoo_password_2025
      - POSTGRES_DB=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo_password_2025
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    volumes:
      - odoo_web_data:/var/lib/odoo
      - odoo_logs:/var/log/odoo
    restart: always
    networks:
      - orbix-network

volumes:
  postgres_data:
  odoo_web_data:
  odoo_logs:

networks:
  orbix-network:
    driver: bridge
