version: '3.8'

services:
  # Servicio principal de Orbix AI
  orbix:
    build: .
    container_name: orbix-ai
    ports:
      - "80:8000"
    env_file:
      - .env
    restart: always
    volumes:
      - ./orbix_config.json:/app/orbix_config.json:ro
    depends_on:
      - postgres
    networks:
      - orbix-network

  # Base de datos PostgreSQL para Odoo
  postgres:
    image: postgres:13
    container_name: orbix-postgres
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo_password_2025
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - orbix-network

  # Odoo para testing de validaciones de tarjetas (Babel)
  odoo:
    build:
      context: .
      dockerfile: Dockerfile.odoo
    container_name: orbix-odoo
    depends_on:
      - postgres
    ports:
      - "8070:8069"
      - "8072:8072"  # Puerto para longpolling
    environment:
      - HOST=postgres
      - USER=odoo
      - PASSWORD=odoo_password_2025
      - DATABASE=odoo
    volumes:
      - odoo_web_data:/var/lib/odoo
      - ./odoo_config:/etc/odoo
      - ./odoo_addons:/mnt/extra-addons
      - odoo_logs:/var/log/odoo
    restart: always
    networks:
      - orbix-network
    command: -- --config=/etc/odoo/odoo.conf --database=odoo --init=base --without-demo=all

volumes:
  postgres_data:
  odoo_web_data:
  odoo_logs:

networks:
  orbix-network:
    driver: bridge
