version: '3.8'
services:
  orbix:
    build: .
    container_name: orbix-ai
    ports:
      - "80:8000"
      - "8000:8000"
    env_file:
      - .env
      - .env.example
    restart: always
    volumes:
      - ./orbix_config.json:/app/orbix_config.json